version: 2.1

install_base_img: &install_base_img
  docker:
    - image: cimg/node:12.16

jobs:
  build:
    <<: *install_base_img
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node_modules
          paths:
            - ./node_modules
      - run: npm run lint

  test:
    <<: *install_base_img
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - node_modules
      - run: npm run test

  analyze:
    <<: *install_base_img
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - node_modules
      - run: npm audit

workflows:
  build_app:
    jobs:
      - build
      - test:
          requires: [ build ]
      - analyze:
          requires: [ test ]
